name: Release Source Maps

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual workflow name"
        required: true

jobs:
   build_ui:
     name: Build UI
     runs-on: "ubuntu-latest"
     steps:
      - uses: actions/checkout@v2
      
      - name: Build Artifact
        run: "make ui_install"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env: 
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with: 
          environment: production
          sourcemaps: web/ui/dashboard/source-maps